---
- name: Deploy web project infrastructure with Docker
  hosts: localhost
  become: yes
  vars:
    project_name: "web_project"
    http_port: 8080
    https_port: 8443
    
    # Версии образов
    apache_version: "2.4"
    php_version: "8.2"
    mysql_version: "8.0"
    kafka_version: "7.4.1"
    
    # MySQL credentials
    mysql_root_password: "secure_root_password"
    mysql_database: "app_db"
    mysql_user: "app_user"
    mysql_password: "secure_db_password"
    
    # Пути для конфигурации
    config_dir: "./config"
    data_dir: "./data"
    web_root: "./www"

  tasks:
    - name: Install Docker and Docker Compose
      block:
        - name: Install required system packages
          apt:
            name: "{{ item }}"
            state: present
            update_cache: yes
          loop:
            - apt-transport-https
            - ca-certificates
            - curl
            - software-properties-common
            - python3-pip

        - name: Add Docker GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker repository
          apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
            state: present

        - name: Install Docker
          apt:
            name: "{{ item }}"
            state: present
          loop:
            - docker-ce
            - docker-ce-cli
            - containerd.io

        - name: Install Docker Compose with pip
          pip:
            name: docker-compose
            state: present

        - name: Add current user to docker group
          user:
            name: "{{ ansible_user }}"
            groups: docker
            append: yes

        - name: Start and enable Docker service
          service:
            name: docker
            state: started
            enabled: yes

    - name: Create project directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - "{{ config_dir }}/apache"
        - "{{ config_dir }}/php"
        - "{{ config_dir }}/mysql"
        - "{{ data_dir }}/mysql"
        - "{{ web_root }}"

    - name: Generate Apache configuration files
      template:
        src: templates/httpd.conf.j2
        dest: "{{ config_dir }}/apache/httpd.conf"
      when: False  # Замените на реальный шаблон или используйте готовый конфиг

    - name: Generate PHP configuration
      copy:
        content: |
          upload_max_filesize = 64M
          post_max_size = 64M
          memory_limit = 256M
          max_execution_time = 300
          display_errors = Off
          log_errors = On
        dest: "{{ config_dir }}/php/php.ini"

    - name: Generate MySQL configuration
      copy:
        content: |
          [mysqld]
          default-authentication-plugin=mysql_native_password
          character-set-server=utf8mb4
          collation-server=utf8mb4_unicode_ci
        dest: "{{ config_dir }}/mysql/my.cnf"

    - name: Generate docker-compose.yml file
      template:
        src: docker-compose.yml.j2
        dest: ./docker-compose.yml

    - name: Create index.php test file
      copy:
        content: |
          <?php
          phpinfo();
          ?>
        dest: "{{ web_root }}/index.php"

    - name: Start containers with Docker Compose
      community.docker.docker_compose:
        project_src: .
        state: present
        pull: yes
        build: no

    - name: Verify containers are running
      command: docker ps
      register: running_containers
      changed_when: False

    - name: Display running containers
      debug:
        var: running_containers.stdout_lines